### ISSUE TITLE
As a user I want to select a card so I can play the card.

### ISSUE THREAD

**Issue by rishson** [dojo/examples#11]
As a User
I want to be presented with a list of cards
So that I can select a card to play in the game.

**Comment by rishson** [comment]
[standard user]
User account does not have admin rights.

**Comment by rishson** [comment]
[successful login]
The user has correctly entered their login credentials.
The user's account is valid (has not expired).

**Comment by rishson** [comment]
https://drive.google.com/drive/folders/0B_iJTK6sYbwKeEwyR2RSTWdjSkU - Cards grid page.

**Comment by agubler** [comment]
Completed.
