### ISSUE TITLE
Evaluate todoMVC for a11y compliance

### ISSUE THREAD

**Issue by rishson** [dojo/examples#114]
Given [out current thinking on a11y](https://docs.google.com/document/d/1PEKPtiVVtNvE-RiZ7kPM14DuZxpZljrBhXK9xaspWX8/edit#), we should evaluate `todoMVC` to see what work would need to be done to meet our guidelines.

**Comment by smhigley** [comment]
Many of the issues seem to be shared by other todoMVC examples, but I assume we should try to fix them anyway. I'll start out with the list below, and see where it goes from there:

**Broken things:**
* Says “deleted” when  you add a new list item using ChromeVox (all TodoMVC examples do this, don't know why yet)
* Can’t focus on “x” unless the mouse is hovered over it, and it doesn’t have an accessible description
* Need focus styles
* toggle all items checkbox needs a label and needs to be before the list; currently visual order and focus order are different
* checkbox to toggle a single item needs a label
* Can’t edit a todo item with the keyboard
* The colors are obviously an issue, but I assume it's not fixable if we want to follow the TodoMVC format
* Should filters in the footer should be radio buttons? They act like it. If they need to be marked up as a list, we can use lots of aria roles and states.
* Should each todo be in the focus order, or should they be navigable with keyboard arrows? (Haven't decided yet, I'll think about it more and any input is welcome)

**Enhancements:**
* Add role=“header” and role=“contentinfo” to header and footer
* Not strictly accessibility, but I think the cursor should be a pointer when hovering over action items like the checkbox and delete button
* There are lots of pseudo-elements in `<input>` elements — I thought this was discouraged? On the other hand, other TodoMVC apps use this, and I'm guessing it's part of the TodoMVC css.

**Comment by rishson** [comment]
@smhigley might be worth finding out which issues are part of `todoMVC`'s css and raising a PR with them to fix?

**Comment by smhigley** [comment]
Definitely. After we get Dojo 2's example accessible, I'll use our changes as a basis for a todoMVC PR.

**Comment by agubler** [comment]
Sounds like the evaluation has been completed 👍
