### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by gbaumgart** [dojo/examples#118]
Hi, 
I am just checking in again after a few months. The results are unfortunately the same again: nothing really works.

Here my trials on ubuntu-x64 and node-v.4.4.7

```bash
cd /tmp (the root of all my trials)
git clone git clone https://github.com/dojo/examples.git

cd examples/dojo-cli-example
npm install

```
gives me : UNMET PEER DEPENDENCY typescript@2.0.2 (happens with all trials)

then i tried just for fun: 

`#grunt`

which gives me: SyntaxError: Unexpected token  (which also happens with all dojo packages i tried)

then i tried the monster-card example:

```
cd examples/monster-cards
npm install (waiting for 10+ mins on recent top-notch hardware with a really speedy glass-fiber connection)
```

Then install went ok, so I navigate to http://localhost/PMaster/x4mm/examples/monster-cards/src/ but nothing but a blank page, so I run

`grunt `
which gives me  SyntaxError: Unexpected token

so I run grunt -v --stack
```bash
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token {
>>   at exports.runInThisContext (vm.js:53:16)
>>   at Module._compile (module.js:373:25)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load (/PMaster/x4mm/examples/monster-cards/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>   at Function.Module._load (module.js:300:12)
>>   at Module.require (module.js:353:17)
>>   at require (internal/module.js:12:17)
>>   at Object.exports.initConfig.combined [as initConfig] (/PMaster/x4mm/examples/monster-cards/node_modules/grunt-dojo2/index.js:72:5)
>>   at Object.module.exports (/PMaster/x4mm/examples/monster-cards/Gruntfile.js:4:25)
>>   at loadTask (/PMaster/x4mm/examples/monster-cards/node_modules/grunt/lib/grunt/task.js:318:10)
>>   at Task.task.init (/PMaster/x4mm/examples/monster-cards/node_modules/grunt/lib/grunt/task.js:437:5)
>>   at Object.grunt.tasks (/PMaster/x4mm/examples/monster-cards/node_modules/grunt/lib/grunt.js:111:8)
>>   at Object.module.exports [as cli] (/PMaster/x4mm/examples/monster-cards/node_modules/grunt/lib/grunt/cli.js:27:9)
>>   at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (module.js:409:26)
>>   at Object.Module._extensions..js (module.js:416:10)
>>   at Module.load (module.js:343:32)
>>   at Function.Module._load (module.js:300:12)
>>   at Function.Module.runMain (module.js:441:10)
>>   at startup (node.js:139:18)
>>   at node.js:968:3

No tasks specified, running default tasks.
Running tasks: default
Warning: Task "default" not found. Use --force to continue.
Error: Task "default" not found.
  at Task.run (/PMaster/x4mm/examples/monster-cards/node_modules/grunt/lib/util/task.js:172:28)
  at /PMaster/x4mm/examples/monster-cards/node_modules/grunt/lib/grunt.js:152:39
  at Array.forEach (native)
  at Object.grunt.tasks (/PMaster/x4mm/examples/monster-cards/node_modules/grunt/lib/grunt.js:152:9)
  at Object.module.exports [as cli] (/PMaster/x4mm/examples/monster-cards/node_modules/grunt/lib/grunt/cli.js:27:9)
  at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:44:20)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3

```

So, that are some trials. I tried other packages as well, but running always in the same errors. I tried also with different typescript installation (-g) but no. 

However, just to let you know. Your packages just don't want to work. If you like I can test this all on other platforms and let you know how it went. 

My biggest fear however seems that you lock dependencies in which:
- make it impossible to zip
- make it impossible to run from a shared network drive
- force me to install dojo packages again on each OS in order to run them at all 

I can also help with more reports and testing, just let me know how to get it work at all. 

thanks, waiting since years to see that happen :-)

**Comment by gbaumgart** [comment]
ah, i may add that the folder /PMaster has been added as symlink in my /htdocs/PMaster

**Comment by bitranch** [comment]
Maybe try updating your dependencies? The readme says "You need to be running node v6+ and npm v3+" which is newer than the node 4 you're running.

**Comment by kitsonk** [comment]
Ref: dojo/dojo2-package-template#61

**Comment by gbaumgart** [comment]
thanks a lot! gonna try.

**Comment by kitsonk** [comment]
also, sometimes you will get `UNMET PEER DEPENDENCY typescript@2.0.2` when using some older versions of some packages that had dependencies that were tied to pre TS2... Usually these are "safe" to ignore.

**Comment by gbaumgart** [comment]
updating to node-v6 made it, thanks a lot again!
