### ISSUE TITLE
Search for cards

### ISSUE THREAD

**Issue by rishson** [dojo/examples#12]
``` gherkin
Given
  standard user
  successful login
When
  the user enters search criteria
  And the user performs a search
Then
  [output] the user should be presented with a list of cards that match the search criteria
  [post condition] clearing the search criteria should remove any filtering of the result set of cards.
```

**Comment by rishson** [comment]
- [search should query the book title and author]
- [search should cope with partial words]
- [search should cope with non-latin unicode characters]
- [search should return results as the search criteria is typed]
- [search should not start returning results until at least 3 characters are typed]

**Comment by dylans** [comment]
The cards demo app has been removed, so closing this issue.
