### ISSUE TITLE
View a monster card's details

### ISSUE THREAD

**Issue by rishson** [dojo/examples#14]
``` cucumber
Given
  standard user
  successful login
When
  the user selects a card from the cards page (monsters or momentum pages)
Then
  output: 
```
- [x] The user should see the details for the selected card on a page devoted entirely to the selected card. 
- [x]   The details should include the card's title, description, large format image of the character, and the details of what the card does.
- [x]   'Last seen with' section should be displayed with medium sized card images.
- [x]   Links to twitter and facebook should be displayed

``` cucumber
  post condition: you should be able to get back to the home page from the card detail page.
   If the user was on a certain 'page' of results on the home page, then going back to the home page should take the user back to the last viewed 'page' of results.
```

**Comment by rishson** [comment]
https://drive.google.com/drive/folders/0B_iJTK6sYbwKeEwyR2RSTWdjSkU - card details page

**Comment by rishson** [comment]
Clickable wires: http://qymfin.axshare.com/cards.html

**Comment by agubler** [comment]
updated to reflect the current implementation, and is completed.
