### ISSUE TITLE
todo-mvc: Should use async instead of setTimeout 0

### ISSUE THREAD

**Issue by kitsonk** [dojo/examples#143]
In todo-mvc `createFocusableTextInput` we are using `setTimeout(fn, 0)` to [set the focus](https://github.com/dojo/examples/blob/9ef02ee526a2ed283b616db02d87f9df489c0985/todo-mvc/src/widgets/createFocusableTextInput.ts#L23).  This can be a performance issue on a number of platforms and there are better ways to cause something to run at the end of the turn.  In particular, this is a micro-task and should then use [`dojo-core/queue#queueMicroTask`](https://github.com/dojo/core/blob/cf7d9b6c3c5ae1305b01577c610ca464ed8812c0/src/queue.ts#L166).

**Comment by smhigley** [comment]
My pull request fixes this, and adds focus styles :)
https://github.com/dojo/examples/pull/134

**Comment by dylans** [comment]
Was fixed a couple of weeks ago, thanks!
