### ISSUE TITLE
Edit todo not working

### ISSUE THREAD

**Issue by agubler** [dojo/examples#162]

**Comment by smhigley** [comment]
On userActions.ts, line 38 (https://github.com/dojo/examples/blob/master/todo-mvc/src/actions/userActions.ts#L37) `todoListState` is returned as an array of one object. It works if you change it to `todoListState[0]`, but I'm not sure if it should be changed in todoMVC or dojo stores.

**Comment by agubler** [comment]
interesting, @maier49 should the stores return back the item rather than an array of 1 item when doing `store.get('id')`?

**Comment by maier49** [comment]
Not currently but we could certainly change it to do so. It was returning an array just for consistency's sake but returning a single item is probably the better option.

**Comment by agubler** [comment]
This has been fixed to the current implementation in https://github.com/dojo/examples/pull/158 and will need to be updated once the return API is updated and released.
