### ISSUE TITLE
Add more features to the kitchen sink

### ISSUE THREAD

**Issue by rorticus** [dojo/examples#183]
* Upgrade to new `@dojo/routing` library.
* Add an example that uses `@dojo/core/request` so we can see the webpack action.
* Add lazy widget loading
* Add CSS theming with CSS modules
* Add i18n
* Add a custom element

**Comment by rorticus** [comment]
This shouldn't have been closed.. still have i18n and lazy widget loading left!

**Comment by rorticus** [comment]
Updated pirate translation on top of https://github.com/dojo/examples/pull/193 . As soon as that is merged, I think this will be about done!

**Comment by dylans** [comment]
> Updated pirate translation on top of #193 . As soon as that is merged, I think this will be about done!

Arrr!
