### ISSUE TITLE
todo-mvc comments

### ISSUE THREAD

**Issue by kitsonk** [dojo/examples#19]
Outside of the MemoryStore which was ported from another repo, the rest of the source code has exactly 2 comments, both of which are `/* I suspect this needs to go somewhere else */` and don't follow the convention of `/* TODO: ... */`.

While things are named logically and TypeScript is somewhat self documenting, the total lack of comments for an example application is not a good idea as those looking to "judge" how our architecture would not be impressed.

**Comment by matt-gadd** [comment]
How are the function names? i'd prefer good function names over a potentially stale verbose jsdoc description as that normally means the function is doing too much (see meaningful names - clean code).

**Comment by matt-gadd** [comment]
We should probably fill out the README properly also, as thats the first page people land on.

**Comment by agubler** [comment]
Agreed, although at the time (and even now) we didn't have all the materials available to link within the README.

**Comment by kitsonk** [comment]
> How are the function names?

They are fine, but that still does not obviate the need for a short description and documenting the parameters in a tsdoc block, as that gives consumers confirmation at design time or when reviewing code sufficient information that they are doing the right thing.

Also, I assume we will want to generate documentation automatically, and when you are lacking any sort of comment, it makes any generated documentation look really 💩 and people then think we have poor API documentation.

> Also lets not conflate code quality with architecture.

I am not conflating the two, I am pointing out that especially for the example applications that people will use to get familiar with Dojo 2 should be rich with additional information...  What is clear to one person is not necessarily clear to everyone else and comments allow you to provide that information.
