### ISSUE TITLE
Integrate ClientErrorReporter into examples

### ISSUE THREAD

**Issue by kitsonk** [dojo/examples#196]
I am getting an issue with master when typing in the field in `kitchensink`:

![kitchensink](https://cloud.githubusercontent.com/assets/1282577/23762251/607a0aa4-04ed-11e7-8f77-e4496f84a830.gif)

**Comment by matt-gadd** [comment]
Looking in the maquette code I imagine I broke this in https://github.com/dojo/widget-core/pull/377

**Comment by matt-gadd** [comment]
Here is the link to the offending line in maquette: https://github.com/AFASSoftware/maquette/blob/master/dist/maquette.js#L139

The options we have are:
* We add an exclusion in our `eventHandlerInterceptor` to fall back to using a standard event handler for `oninput`
* We add exclusions for all the maquette supported events in the `eventHandlerInterceptor`
* We submit a fix to maquette to be more defensive and function check before calling (although this might then exhibit the bug)
* We roll back dojo/widget-core#377 and lose pointer event support via polyfill for now

**Comment by kitsonk** [comment]
> - We submit a fix to maquette to be more defensive and function check before calling (although this might then exhibit the bug it's meant to fix)

I would vote for that.  They might argue that being more defensive is "overhead" but they are blindly assuming there is still a target there, which maybe incorrect.

**Comment by dylans** [comment]
I believe this issue has been resolved.

**Comment by kitsonk** [comment]
No the `ClientErrorCollector` from `test-extras` has not been integrated into this repo.

**Comment by kitsonk** [comment]
Closing in favour of #209
