### ISSUE TITLE
Setting routes in an application

### ISSUE THREAD

**Issue by dylans** [dojo/examples#214]
Our todo examples have a filterRoute implementation with a note:

TODO find a better place for this

So let's find a better place for this utility/convenience method.

**Comment by kitsonk** [comment]
I suspect that will fall under the umbrella of "app" as our routes, any middleware, application state, etc would be orchestrated by whatever _app_ is.

**Comment by agubler** [comment]
I think this has been removed now since the introduction of declarative routing with `Outlets`
