### ISSUE TITLE
Design showcase page

### ISSUE THREAD

**Issue by kitsonk** [dojo/examples#247]
@bitpshr commented on [Tue Oct 24 2017](https://github.com/dojo/widgets/issues/330)

**Enhancement**

Our showcase page at https://dojo.github.io/widgets/ is pretty ugly. It would be great to get a mock up that we can implement to make it look nicer.

Package Version: latest

---

@kitsonk commented on [Tue Oct 24 2017](https://github.com/dojo/widgets/issues/330#issuecomment-339064445)

We also discussed with @agubler and @matt-gadd that we should consider moving it to `dojo/examples` as well?

**Comment by kitsonk** [comment]
Actually taking a look at my notes from the planning meeting, we are going to ask @umaar to migrate the showcase to the examples.  We should do that wholesale as a first step and then we can do the design.  I am going to open up a couple of other issues to help facilitate that and have moved this issue, as it will exist here fore now.

**Comment by umaar** [comment]
The showcase page lives in this repo now: https://dojo.github.io/examples/widget-showcase/

Let me know if there's a design I should be following 👍
