### ISSUE TITLE
Update the widget showcase to use beta 4

### ISSUE THREAD

**Issue by umaar** [dojo/examples#264]
The widget showcase has Dojo 2 [dependencies](https://github.com/dojo/examples/blob/d9f0240336fa50193f35acf25a2446d47725e3d9/widget-showcase/package.json#L8-L14), these deps can be upgraded to use beta 4.

See this as an example: https://github.com/dojo/examples/pull/262

https://github.com/dojo/examples/blob/d9f0240336fa50193f35acf25a2446d47725e3d9/widget-showcase/package.json#L8-L14

**Comment by bitpshr** [comment]
Resolved by #271. More dependency updates were also done as part of #272.
