### ISSUE TITLE
Demonstrate usage of meta's from widget-core

### ISSUE THREAD

**Issue by matt-gadd** [dojo/examples#268]
None of the example apps currently demonstrate any of the meta's in widget-core (`animations`, `intersection`, `drag`). We should consider either adding them to the kitchen-sink, or creating a separate demo app just for meta's.

**Comment by agubler** [comment]
Intersection observer example has landed #318

**Comment by agubler** [comment]
There is examples of both intersection and resize metas (soon to be middleware)
