### ISSUE TITLE
Reg. Dojo 2 Flat Theme

### ISSUE THREAD

**Issue by vbhanuc87** [dojo/examples#275]
More of a question. Is there going to be a default theme like claro / soria / FLAT for dojo 2 ?

Can the widget showcase modified to use any of the dojo 1 themes ? More interested in the Flat theme and if it is supported already, can you provide any pointers to the blog / article / tutorial.

**Comment by tomdye** [comment]
We are working on an initial theme for the Dojo 2 widgets that is simply named `dojo`. It is relatively flat but is still in it's early development phase. You can view the currently offered widgets rendered using the `dojo` theme [here](https://dojo.github.io/examples/widget-showcase) on our widget showcase example page.

All of the Dojo 2 widgets are fully themable via our theming process which is documented both in the [readme](https://github.com/dojo/widget-core#styling--theming) and in the [theming tutorial](https://dojo.io/tutorials/007_theming/). 

We are also currently working on a `cli` command which will assist with the process of writing a new theme by providing a scaffolded theme directory and in future are likely to move the `themes` directory out of `@dojo/widgets` and into it's own repo.

I'm afraid that the Dojo 1.x themes cannot be used with Dojo 2 widgets as the dom structure, class usage and underlying technologies have changed dramatically.

**Comment by dylans** [comment]
My plan, once things had stabilized with themes, was to offer a theme for Dojo 2 that is consistent with the 1.x flat theme. This will help with interoperability between Dojo 1 and 2.

**Comment by vbhanuc87** [comment]
Awesome @dylans. Thank you very much and looking forward for a flat theme in dojo 2. With that addition, it would be really helpful to convince my teams to stick with the awesome dojo framework.
