### ISSUE TITLE
esoteric work with resources

### ISSUE THREAD

**Issue by ShadowTeolog** [dojo/examples#291]
After two days of code reading and experiments, add *.png image directory with keep names and relative path to final build still unsuccessful.
This need because lot of svg images with relative linked resources, so resource path need to be unchanged. Embed images to svg currently not possible, this break develop process.
So currently migrate from dojo 1.x to 2.x look impossible.
I believe this possible for current build system, but need working example how to do this.

**Comment by dylans** [comment]
Hi @ShadowTeolog Ok, I think I understand the issue... could you please open an issue with a simple example in the https://github.com/dojo/cli-build-app repo and we'll investigate?

**Comment by agubler** [comment]
Hey @ShadowTeolog can you add an issue to the correct repo as @dylans mentioned above?

**Comment by agubler** [comment]
Closing, if this is still an issue please raise against the repository suggested above.
