### ISSUE TITLE
widget showcase and mobile

### ISSUE THREAD

**Issue by dylans** [dojo/examples#293]
New widget showcase looks great on desktop, but isn't usable on mobile (at least iOS):

* Unable to select theme
* Unable to see items on right side in portrait orientation (split pane is unreliable with touch events)
* Hamburger menu has no actions
* Disabled checkboxes can be toggled
* Toggle starts out with dark black background

**Comment by dylans** [comment]
Note the currently deployed version of the widget showcase seems to have a very broken left side: 
![screenshot 2018-02-24 06 50 12](https://user-images.githubusercontent.com/97291/36631103-42e5cc56-192f-11e8-915d-69442678e6fb.png)

**Comment by dylans** [comment]
Note my previous comment is caused by https://github.com/dojo/widgets/issues/449

**Comment by agubler** [comment]
This has been resolved (verified on ios):

* Theme can be selected on mobile
* Splitpane stacks for mobile now
* Hamburger menu doesn't show if no actions
* Disabled checkboxes can not be toggled
* Toggle starts are themed correctly
