### ISSUE TITLE
todo-mvc-kitchensink item checkbox missing

### ISSUE THREAD

**Issue by devpaul** [dojo/examples#316]
A checkbox should be present to the left of TODO items. It is missing on the [todo-mvc-kitchensink demo](https://dojo.github.io/examples/todo-mvc-kitchensink/#view/list?filter=all). Clicking to the left still marks the item complete.

<img width="952" alt="screen shot 2018-03-31 at 4 55 43 pm" src="https://user-images.githubusercontent.com/331431/38168561-87de9932-3504-11e8-994f-75645067ddb5.png">

**Comment by matt-gadd** [comment]
This seems to be an issue with firefox/edge specifically for the todo-mvc-css (see: https://github.com/tastejs/todomvc-app-css/issues/26). 

to fix is a case of applying these changes: https://github.com/tastejs/todomvc-app-css/pull/8 to our css.

**Comment by agubler** [comment]
Fixed
