### ISSUE TITLE
custom-element-menu can not render at firefox 59.0.2

### ISSUE THREAD

**Issue by xiaohulu** [dojo/examples#317]
https://dojo.github.io/examples/custom-element-menu/

throw errors:
```
TypeError: c.a.customElements is undefined             registerCustomElement.mjs:210
```

browser: firefox 59.0.2

**Comment by agubler** [comment]
(I'm using a mac)

**Comment by xiaohulu** [comment]
I am using windows 10

**Comment by xiaohulu** [comment]
![firefox-custom](https://user-images.githubusercontent.com/624517/38284685-29343962-37ef-11e8-8e57-d933a9bf83fc.png)
![error](https://user-images.githubusercontent.com/624517/38284688-2c065c6a-37ef-11e8-8bc0-b5cfc9f85cab.png)

**Comment by agubler** [comment]
@xiaohulu that's really strange, on a VM running Windows 10 and using Firefox 59.0.2 the custom element menu runs as expected.

<img width="1158" alt="msedge_-_win10__running_" src="https://user-images.githubusercontent.com/1982678/38311258-a9b504aa-3816-11e8-942c-96701334c989.png">
