### ISSUE TITLE
Attempting to run realworld example - buildingfs error

### ISSUE THREAD

**Issue by ktiedt** [dojo/examples#328]
```
~/Projects/examples/realworld$ npm run dev

> realworld-app@1.0.0 dev /Users/karl.tiedt/Projects/examples/realworld
> dojo build -m dev -s -w memory

⠸ buildingfs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/karl.tiedt/Projects/examples/realworld/output/dev/index.html'
```

```
~/Projects/examples/realworld$ node --version
v8.10.0
~/Projects/examples/realworld$ dojo --version
2.0.0
```

**Comment by mwistrand** [comment]
Thanks, @ktiedt. This particular error emerges from the build-time rendering, which we plan to [disable with `--watch memory`](https://github.com/dojo/cli-build-app/issues/77). In the meantime, if you run the build without the memory flag (so `dojo build -m dev -s -w`), you will be able to build and interact with the application.

**Comment by ktiedt** [comment]
Thanks @mwistrand that does in fact get things moving.
