### ISSUE TITLE
Live custom element showcase does not load properly

### ISSUE THREAD

**Issue by mwistrand** [dojo/examples#329]
At the moment the [live custom element showcase](https://dojo.github.io/examples/custom-element-showcase/) throws 404 errors for `themes/dojo-2.0.0.js` and `themes/dojo-2.0.0.css`, with the result that only the calendar is rendered (but still cannot be interacted with).

The file names in the dist directory are incorrect; both `@dojo/themes` and `@dojo/widgets` need to be released to 2.0.1.

**Comment by agubler** [comment]
resolved by #331
