### ISSUE TITLE
Non-functionals

### ISSUE THREAD

**Issue by rishson** [dojo/examples#37]
Build the app:

- [ ] any perf work (concat, minification..)
- [ ] generate sourcemaps
- [ ] build layer file

**Comment by rishson** [comment]
Please add tasks as appropriate.

**Comment by agubler** [comment]
@rishson can this separated out into it's own story...?

**Comment by agubler** [comment]
It doesn't feel like it should be part of the `Page Layouts` epic....

**Comment by rishson** [comment]
@matt-gadd can I close as will be covered in your webpack build?
I'll raise a separate issue for building layer files.

**Comment by agubler** [comment]
Yep this can be closed and raised in a more appropriate location (probably CLI)
