### ISSUE TITLE
Monster Cards Pinned Versions

### ISSUE THREAD

**Issue by kitsonk** [dojo/examples#49]
The versions of Maquette and Immutable are pinned for Monster Cards:

```json
{
  "dependencies": {
    "immutable": "3.8.1",
    "maquette": "2.3.2"
  }
}
```

They should be more properly semvered.  Currently this is causing the following warning on `npm install`:

```
npm WARN dojo-widgets@2.0.0-alpha.8 requires a peer of maquette@^2.3.5 but none was installed.
```

**Comment by agubler** [comment]
these deps have been updated.
