### ISSUE TITLE
Update header widget to latest wires. 

### ISSUE THREAD

**Issue by rishson** [dojo/examples#50]
https://drive.google.com/drive/folders/0B_iJTK6sYbwKeEwyR2RSTWdjSkU / 01_home.png

**Comment by agubler** [comment]
Are these the "final" wires?

**Comment by rishson** [comment]
No wires are ever final. Thought I'd do this issue to help me understand things better and get you to check?

**Comment by agubler** [comment]
Of course wires are final, as I do not see the value constantly updating parts of this example application as wires are tweaked...

**Comment by rishson** [comment]
@agubler can close?
