### ISSUE TITLE
Update MonsterCards with initial i18n implementation.

### ISSUE THREAD

**Issue by rishson** [dojo/examples#61]

**Comment by mwistrand** [comment]
For all intents and purposes, this is completed. However, `dojo-widgets/mixins/createI18nMixin` is built on the latest `dojo-widgets` `master`, which for various reasons, is indirectly incompatible with the latest `dojo-app`. As such, when relying on the latest `dojo-widgets`, state is not properly updated and the application does not function as intended.

**Comment by dylans** [comment]
monster cards app has been removed from dojo/examples.
