### ISSUE TITLE
Update todoMVC with initial i18n implementation.

### ISSUE THREAD

**Issue by rishson** [dojo/examples#62]

**Comment by mwistrand** [comment]
For all intents and purposes, this is completed. However, `dojo-widgets/mixins/createI18nMixin` is built on the latest `dojo-widgets` `master`, which for various reasons, is indirectly incompatible with the latest `dojo-app`. As such, when relying on the latest `dojo-widgets`, state is not properly updated and the application does not function as intended.

**Comment by agubler** [comment]
You can reply on master of app and widgets?

**Comment by mwistrand** [comment]
For `dojo-app`, yes. For `dojo-widgets`, no. If I symlink to widgets/master, then I run into the same issues I do when symlinking to the branch that has `createI18nMixin`. However, symlinking to `v2.0.0-alpha.10` does work.

**Comment by rishson** [comment]
@mwistrand - is this still a live issue?

**Comment by agubler** [comment]
@rishson this has been done in todo-mvc-kitchensink - I think it can be closed.

**Comment by rishson** [comment]
👍
