### ISSUE TITLE
ToDoMVC performance test

### ISSUE THREAD

**Issue by dylans** [dojo/examples#66]
Around beta, we should make a performance test available for comparison, either a fork of https://github.com/evancz/todomvc-perf-comparison or https://github.com/kriszyp/todomvc-perf-comparison

**Comment by agubler** [comment]
We should probably do this sooner rather than later, in case there is anything that needs addressing.

**Comment by matt-gadd** [comment]
@agubler is it worth posting our earlier tests pre `d`, and post `d` here for posterity? we can then keep tracking performance as we progress.

**Comment by agubler** [comment]
@matt-gadd nice idea.

**Comment by agubler** [comment]
Some benching marking results using `https://github.com/kriszyp/todomvc-perf-comparison`:

*Pre `d` widget management*:
<img width="495" alt="todomvc_benchmark" src="https://cloud.githubusercontent.com/assets/1982678/20844637/bd43db56-b8b8-11e6-98ac-042bc847bb1d.png">

*Post `d` widget management*:
<img width="478" alt="todomvc_benchmark-1" src="https://cloud.githubusercontent.com/assets/1982678/20844677/edd1bf0e-b8b8-11e6-9a94-68642835b346.png">

It's more important to focus on the comparison of `dojo2` timings than the comparison of `dojo2` against the other frameworks (as they are using a static version todo-mvc contained in https://github.com/kriszyp/todomvc-perf-comparison repo)

**Comment by agubler** [comment]
In fact I use https://github.com/agubler/todomvc-perf-comparison which has the [tastejs todomvc examples](https://github.com/tastejs/todomvc/tree/master/examples) sub-moduled and extra tests added for `dojo`, `vue`, `typescript-react` (and more)

**Comment by agubler** [comment]
Current perf metrics for `widget-core` release 2.0.0-beta1.4 running for 100 todos.

<img width="798" alt="todomvc_benchmark" src="https://cloud.githubusercontent.com/assets/1982678/25802914/6eb9b65e-33ec-11e7-9d29-14fd098f92a6.png">

**Comment by agubler** [comment]
We have implemented js-framework-benchmark tests to run as part of CI on widget-core, which can provide a mechanism to track performance. I think this issue can now be closed.
