### ISSUE TITLE
todoMVC: new to-dos not added after completed are cleared.

### ISSUE THREAD

**Issue by mwistrand** [dojo/examples#74]
Steps to reproduce (tested in FF latest and Chrome latest):
1. Add any number of to-dos.
2. Mark all to-dos as completed.
3. Click "Clear completed".
4. Add more to-dos.

Expected result:
The new to-dos should be rendered as part of the to-do list.

Actual result:
The new to-dos are not rendered, even though the footer text (e.g., "1 item left") is updated.

**Comment by agubler** [comment]
This should have been addressed by https://github.com/dojo/widgets/issues/75

**Comment by matt-gadd** [comment]
this is now fixed so closing.
