### ISSUE TITLE
readonly visibility modifier for TS2.0+

### ISSUE THREAD

**Issue by kitsonk** [dojo/examples#8]

**Comment by rishson** [comment]
@matt-gadd @agubler - do we need to revisit the todo code and make sure this is done, or are we good to go?

**Comment by agubler** [comment]
We haven't used the `readonly` syntax for todo (or indeed) through most of the dojo2 code base yet.

**Comment by agubler** [comment]
I'm not sure there is much to do for this issue within TodoMVC.
